routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');

Auth::routes();

Route::get('data_view_json', 'PageController@data_view_json')->name('data_view_json');
Route::get('testimonials/{id}', 'PageController@testimonials')->name('testimonials');
Route::post('register_appointment', 'Admin\QuotesController@register_appointment')->name('register_appointment');
Route::post('save_testimonial', 'PageController@save_testimonial')->name('save_testimonial');

Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('calendar', 'CalendarController', ['as' => 'admin']);
     Route::resource('quotes', 'QuotesController', ['as' => 'admin']);
     Route::resource('packages', 'PackagesController', ['as' => 'admin']);
     Route::resource('configuration', 'ConfigurationController', ['as' => 'admin']);
     Route::resource('testimonials', 'TestimonialsController', ['as' => 'admin']);
     Route::resource('gallery', 'GalleryController', ['as' => 'admin']);
     Route::resource('cleaning_need', 'CleaningNeedsController', ['as' => 'admin']);
     Route::resource('contact_images', 'ContactImagesController', ['as' => 'admin']);
     Route::resource('disable_day', 'DisableDayController', ['as' => 'admin']);
     Route::get('quotes/finish_quote/{id}', 'QuotesController@finish_quote')->name('admin.quotes.finish_quote');

});

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Images;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class GalleryController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index()
     {
          $images = Images::all();
          return view('admin.gallery.index', compact('images'));
     }

     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create()
     {
          $images = new Images;
          return view('admin.gallery.create', compact('images'));
     }

     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(Request $request)
     {

          $data = $request->validate([
               'photo' => 'required'
          ]);

          $data['status'] = 1;

          if ($request->file('photo') != null) {
               $photo = $request->file('photo')->store('public');
               $data['photo'] = Storage::url($photo);
          }

          $packages = Images::create($data)->id;

          return redirect()->route('admin.gallery.index')->with('success', 'Imagen registrada');
     }

     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function show(Packages $packages)
     {
          return view('admin.gallery.show', compact('packages'));
     }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function edit($id)
     {
          $images = Images::find($id);
          return view('admin.gallery.edit', compact('images'));
     }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function update(Request $request, $id)
     {
          $imagen = Images::find($id);

          $data = $request->validate([
               'photo' => 'required'
          ]);

          $data['status'] = 1;


          if ($request->file('photo') != null) {
               $photo = $request->file('photo')->store('public');
               $data['photo'] = Storage::url($photo);
          }

          $imagen->update( $data );

          return redirect()->route('admin.gallery.index')->with('success', 'Paquete actualizado');
     }

     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id)
     {
          $Images = Images::find($id);
          $Images->delete();
          return back()->with('success', 'Administrador eliminado');

     }
}

resources/views/admin/gallery/create.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-8 ml-auto mr-auto">
     <form class="form" method="post" enctype="multipart/form-data" action="{{ route('admin.gallery.store') }}">
          {{ csrf_field() }}

          <div class="card">
               <div class="card-header ">
                    <h3 class="card-title">Registrar paquete</h3>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                              <ul class="list-group">
                                   @foreach($errors->all() as $key => $error)
                                   <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                   @endforeach
                              </ul>
                              @endif
                         </div>
                         <div class="col-md-12">
                              <div class="row">
                                   <div class="col-md-12 text-center">
                                        <label for="email">Activo</label><br>
                                        <input type="checkbox" name="status" value="1" checked data-bootstrap-switch >
                                   </div>
                              </div>
                              <hr>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="name">Imagen</label>
                                             <div class="row">
                                                  <div class="col-md-12 div_img">
                                                       <div class="alert"></div>
                                                       <div id='img_container'><img id="preview" src="https://webdevtrick.com/wp-content/uploads/preview-img.jpg" alt="your image" title=''/></div>
                                                       <div class="input-group">
                                                            <div class="custom-file">
                                                                 <input type="file" name="photo" id="inputGroupFile01" class="imgInp custom-file-input" aria-describedby="inputGroupFileAddon01" accept="image/*">
                                                                 <label class="custom-file-label" for="inputGroupFile01">Elija el archivo</label>
                                                            </div>
                                                       </div>
                                                  </div>

                                             </div>
                                        </div>
                                   </div>
                              </div>


                         </div>

                    </div>


               </div>
               <div class="card-footer">
                    <button type="submit" class="btn btn-info btn-fill float-right">Agregar imagen</button>
                    <a href="{{ route('admin.packages.index') }}" class="btn btn-default btn-fill float-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>

@stop

@push('style')
<style media="screen">
.alert{
     text-align:center;
}

#preview{
     max-height:256px;
     height:auto;
     width:auto;
     display:block;
     margin-left: auto;
     margin-right: auto;
     padding:5px;
}
#img_container{
     border-radius:5px;
     margin-top:20px;
     width:auto;
}

.imgInp{
     width:150px;
     margin-top:10px;
     padding:10px;
     background-color:#d3d3d3;
}
.loading{
     animation:blinkingText ease 2.5s infinite;
}
@keyframes blinkingText{
     0%{     color: #000;    }
     50%{   color: #transparent; }
     99%{    color:transparent;  }
     100%{ color:#000; }
}
.custom-file-label{
     cursor:pointer;
}

.div_img{
     background-color: #eee;
     border-radius: 5px;
     padding: 10px;
}
.custom-file-input:lang(en) ~ .custom-file-label::after {
    content: "Navegar";
}
</style>
@endpush


<!-- Escripts pasarlos al layout -->
@push('scripts')
<script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
<script src="{{ asset('/theme/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>
<script>
// CKEDITOR.replace( 'description' );
$(function () {
     $("input[data-bootstrap-switch]").each(function(){
          $(this).bootstrapSwitch('state', $(this).prop('checked'));
     });
});
$("#inputGroupFile01").change(function(event) {
     RecurFadeIn();
     readURL(this);
});

$("#agregar_tarea").on('click',function(event){
     $( "#tareas" ).append( '<div style="display: flex; margin-bottom: 10px;"><input name="tasks[]"  class="form-control"  placeholder="tarea" ><button type="button" class="btn btn-sm btn-danger delete_task" ><i class="fa fa-trash" aria-hidden="true"></i></button></div>' );
});

$(document).on('click',".delete_task", function(){
      $(this).parent().remove();
})

$("#inputGroupFile01").on('click',function(event){
     RecurFadeIn();
});
function readURL(input) {
     if (input.files && input.files[0]) {
          var reader = new FileReader();
          var filename = $("#inputGroupFile01").val();
          filename = filename.substring(filename.lastIndexOf('\\')+1);
          reader.onload = function(e) {
               debugger;
               $('#preview').attr('src', e.target.result);
               $('#preview').hide();
               $('#preview').fadeIn(500);
               $('.custom-file-label').text(filename);
          }
          reader.readAsDataURL(input.files[0]);
     }
     $(".alert").removeClass("loading").hide();
}
function RecurFadeIn(){
     console.log('ran');
     FadeInAlert("Wait for it...");
}
function FadeInAlert(text){
     $(".alert").show();
     $(".alert").text(text).addClass("loading");
}
</script>

@endpush

resources/views/admin/gallery/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-8 ml-auto mr-auto">
     <form class="form" method="post" enctype="multipart/form-data" action="{{ route('admin.gallery.update', $images) }}">
          {{ csrf_field() }} {{ method_field('PUT') }}

          <div class="card">
               <div class="card-header ">
                    <h3 class="card-title">Editar imagen</h3>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                              <ul class="list-group">
                                   @foreach($errors->all() as $key => $error)
                                   <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                   @endforeach
                              </ul>
                              @endif
                         </div>
                         <div class="col-md-12">
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="name">Imagen</label>
                                             <div class="row">
                                                  <div class="col-md-12 div_img">
                                                       <div class="alert"></div>
                                                       <div id='img_container'><img id="preview" src="
                                                            @if($images->photo)
                                                                 {{ $images->photo }}
                                                            @else
                                                                 https://webdevtrick.com/wp-content/uploads/preview-img.jpg
                                                            @endif
                                                            " alt="your image" title=''/></div>
                                                       <div class="input-group">
                                                            <div class="custom-file">
                                                                 <input type="file" name="photo" id="inputGroupFile01" class="imgInp custom-file-input" aria-describedby="inputGroupFileAddon01" accept="image/*">
                                                                 <label class="custom-file-label" for="inputGroupFile01">Elija el archivo</label>
                                                            </div>
                                                       </div>
                                                  </div>

                                             </div>
                                        </div>
                                   </div>
                              </div>
                         </div>

                    </div>
               </div>
               <div class="card-footer">
                    <button type="submit" class="btn btn-info btn-fill float-right">Editar imagen</button>
                    <a href="{{ route('admin.gallery.index') }}" class="btn btn-default btn-fill float-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>
@stop

@push('style')
<style media="screen">
.alert{
     text-align:center;
}

#preview{
     max-height:256px;
     height:auto;
     width:auto;
     display:block;
     margin-left: auto;
     margin-right: auto;
     padding:5px;
}
#img_container{
     border-radius:5px;
     margin-top:20px;
     width:auto;
}

.imgInp{
     width:150px;
     margin-top:10px;
     padding:10px;
     background-color:#d3d3d3;
}
.loading{
     animation:blinkingText ease 2.5s infinite;
}
@keyframes blinkingText{
     0%{     color: #000;    }
     50%{   color: #transparent; }
     99%{    color:transparent;  }
     100%{ color:#000; }
}
.custom-file-label{
     cursor:pointer;
}

.div_img{
     background-color: #eee;
     border-radius: 5px;
     padding: 10px;
}
.custom-file-input:lang(en) ~ .custom-file-label::after {
    content: "Navegar";
}
</style>
@endpush


<!-- Escripts pasarlos al layout -->
@push('scripts')
<script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
<script src="{{ asset('/theme/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>
<script>
// CKEDITOR.replace( 'description' );
$(function () {
     $("input[data-bootstrap-switch]").bootstrapSwitch();
});
$("#inputGroupFile01").change(function(event) {
     RecurFadeIn();
     readURL(this);
});
$("#inputGroupFile01").on('click',function(event){
     RecurFadeIn();
});

$("#agregar_tarea").on('click',function(event){
     $( "#tareas" ).append( '<div style="display: flex; margin-bottom: 10px;"><input name="n[]"  class="form-control"  placeholder="tarea" ><button type="button" class="btn btn-sm btn-danger delete_task" ><i class="fa fa-trash" aria-hidden="true"></i></button></div>' );
});

$(document).on('click',".delete_task", function(){
      $(this).parent().remove();
})

function readURL(input) {
     if (input.files && input.files[0]) {
          var reader = new FileReader();
          var filename = $("#inputGroupFile01").val();
          filename = filename.substring(filename.lastIndexOf('\\')+1);
          reader.onload = function(e) {
               debugger;
               $('#preview').attr('src', e.target.result);
               $('#preview').hide();
               $('#preview').fadeIn(500);
               $('.custom-file-label').text(filename);
          }
          reader.readAsDataURL(input.files[0]);
     }
     $(".alert").removeClass("loading").hide();
}
function RecurFadeIn(){
     console.log('ran');
     FadeInAlert("Wait for it...");
}
function FadeInAlert(text){
     $(".alert").show();
     $(".alert").text(text).addClass("loading");
}
</script>

@endpush

resources/views/admin/gallery/index.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-12">
     <div class="card ">
          <div class="card-header ">
               <h3 class="card-title">Galería</h3>
               <!-- <div class="card-tools">
                    <a href="{{ route('admin.gallery.create') }}" class="btn btn-success btn-sm">
                         <i class="fa fa-plus"></i> Nuevo
                    </a>
               </div> -->
          </div>
          <div class="card-body table-responsive">
               <table class="table table-hover table-striped table_js">
                    <thead>
                         <tr>
                              <th>ID</th>
                              <th class="text-center">Imagen</th>
                              <!-- <th class="text-center">Estatus</th> -->
                              <th class="text-center"><i class="nc-icon nc-preferences-circle-rotate"></i></th>
                         </tr>
                    </thead>
                    <tbody>
                         @foreach ($images as $img)
                         <tr>
                              <td>{{ $img->id }}</td>
                              <td class="text-center"> <img src="{{ $img->photo }}" class="img-fluid" style="width:80px;" alt=""> </td>
                              <!-- <td class="text-center">
                                   @if($img->status == 1)
                                        <h6><span class="badge badge-success">Activo</span></h6>
                                   @else
                                        <h6><span class="badge badge-danger">Inactivo</span></h6>
                                   @endif
                              </td> -->
                              <td class="text-center">
                                   <!-- <a href="{{ route('admin.packages.show', $img) }}"
                                        class="btn btn-sm  btn-outline-primary"
                                   > <i class="fas fa-address-card"></i> </a> -->

                                   <a href="{{ route('admin.gallery.edit', $img) }}"
                                        class="btn btn-sm btn-outline-info"
                                   > <i class="fas fa-edit"></i> </a>

                                   <!-- <form method="POST"
                                        action="{{ route('admin.gallery.destroy', $img) }}"
                                        style="display:inline">
                                        {{ csrf_field() }} {{ method_field('DELETE') }}
                                        <button class="btn btn-sm btn-outline-danger"
                                             onclick="return confirm('¿ Estás seguro de querer eliminar esta imagen ?')"
                                         >
                                        <i class="fas fa-trash"></i>
                                        </button>
                                   </form> -->
                              </td>
                         </tr>
                         @endforeach
                    </tbody>
               </table>
          </div>
     </div>
</div>
@stop