routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');

Auth::routes();

Route::get('data_view_json', 'PageController@data_view_json')->name('data_view_json');
Route::get('testimonials/{id}', 'PageController@testimonials')->name('testimonials');
Route::post('register_appointment', 'Admin\QuotesController@register_appointment')->name('register_appointment');
Route::post('save_testimonial', 'PageController@save_testimonial')->name('save_testimonial');

Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('calendar', 'CalendarController', ['as' => 'admin']);
     Route::resource('quotes', 'QuotesController', ['as' => 'admin']);
     Route::resource('packages', 'PackagesController', ['as' => 'admin']);
     Route::resource('configuration', 'ConfigurationController', ['as' => 'admin']);
     Route::resource('testimonials', 'TestimonialsController', ['as' => 'admin']);
     Route::resource('gallery', 'GalleryController', ['as' => 'admin']);
     Route::resource('cleaning_need', 'CleaningNeedsController', ['as' => 'admin']);
     Route::resource('contact_images', 'ContactImagesController', ['as' => 'admin']);
     Route::resource('disable_day', 'DisableDayController', ['as' => 'admin']);
     Route::get('quotes/finish_quote/{id}', 'QuotesController@finish_quote')->name('admin.quotes.finish_quote');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'last_name_paternal', 'last_name_maternal', 'status', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
     {
          $users = User::all();
          return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $user = new User;
         return view('admin.users.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $data = $request->validate([
             'name' => 'required|string|max:255',
             'email' => 'required|string|email|max:255|unique:users'
        ]);

        $data['status'] = request('status') == 1 ? 1 : 0 ;
        $data['last_name_paternal'] = request('last_name_paternal');
        $data['last_name_maternal'] = request('last_name_maternal');
        $data['password'] = Hash::make(str_random(8));

        $user = User::create($data);

        // UserWasCreated::dispatch($user, $data['password']);

        return redirect()->route('admin.user.index')->with('success', 'Administrador registrado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
         return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
         $data = $request->validate([
             'name' => 'required|string|max:255',
             'email' => 'required|string|email|max:255|unique:users,email,'.$user->id,
        ]);

        if($request->filled('password')) {
           $data =  $request->validate([
                  'password' => 'confirmed', 'min:7',
             ]);
        }

        $data['last_name_paternal'] = request('last_name_paternal');
        $data['last_name_maternal'] = request('last_name_maternal');
        $data['status'] = request('status') == 1 ? 1 : 0 ;
        $data['password'] = Hash::make(request('password'));

        $user->update( $data );

        return redirect()->route('admin.user.index')->with('success', 'Administrador actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
          $user->delete();
          return back()->with('success', 'Administrador eliminado');

    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-8 ml-auto mr-auto">
     <form class="form" method="post" action="{{ route('admin.user.store') }}">
          {{ csrf_field() }}

          <div class="card">
               <div class="card-header ">
                    <h3 class="card-title">Registrar Administrador</h3>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                              <ul class="list-group">
                                   @foreach($errors->all() as $key => $error)
                                   <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                   @endforeach
                              </ul>
                              @endif
                         </div>
                         <div class="col-md-12">
                              <div class="row">
                                   <div class="col-md-8">
                                        <div class="form-group">
                                             <label for="name">Nombre(s)</label>
                                             <input type="text" name="name" class="form-control" value="{{ old('name') }}" placeholder="Nombre">
                                        </div>
                                   </div>
                                   <div class="col-md-4 text-center">
                                        <label for="email">Acceso</label><br>
                                        <input type="checkbox" name="status" value="1" checked data-bootstrap-switch >
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="name">Apellido Paterno</label>
                                             <input type="text" name="last_name_paternal" class="form-control" value="{{ old('last_name_paternal') }}" placeholder="Apellido Paterno">
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="last_name_maternal">Apellido Materno</label>
                                             <input type="text" name="last_name_maternal" class="form-control" value="{{ old('last_name_maternal') }}" placeholder="Apellido Materno">
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="email">Correo</label>
                                             <input type="email" name="email" class="form-control" value="{{ old('email') }}" placeholder="Correo">
                                        </div>
                                   </div>

                              </div>
                         </div>
                         <div class="col-md-12">
                              <hr>
                         </div>
                         <div class="col-md-12">
                              <span class="help-block"> La contraseña será generada y enviada al nuevo usuario vía correo.</span>
                         </div>
                         <div class="col-md-12">
                              <hr>
                         </div>
                    </div>


               </div>
               <div class="card-footer">
                    <button type="submit" class="btn btn-info btn-fill float-right">Agregar administrador</button>
                    <a href="{{ route('admin.user.index') }}" class="btn btn-default btn-fill float-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>
@stop

@push('style')

@endpush


<!-- Escripts pasarlos al layout -->
@push('scripts')
<script src="{{ asset('/theme/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>
<script>
$(function () {
     $("input[data-bootstrap-switch]").each(function(){
          $(this).bootstrapSwitch('state', $(this).prop('checked'));
     });
});
</script>

@endpush

resources/views/admin/users/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-8 ml-auto mr-auto">
     <form class="form" method="post" action="{{ route('admin.user.update', $user) }}">
          {{ csrf_field() }} {{ method_field('PUT') }}

          <div class="card">
               <div class="card-header ">
                    <h3 class="card-title">Editar administrador</h3>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                              <ul class="list-group">
                                   @foreach($errors->all() as $key => $error)
                                   <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                   @endforeach
                              </ul>
                              @endif
                         </div>
                         <div class="col-md-12">
                              <div class="row">
                                   <div class="col-md-8">
                                        <div class="form-group">
                                             <label for="name">Nombre(s)</label>
                                             <input type="text" name="name" class="form-control" value="{{ old('name', $user->name) }}" placeholder="Nombre">
                                        </div>
                                   </div>
                                   <div class="col-md-2 text-center">
                                        <label for="email">Acceso</label><br>
                                        <input type="checkbox" name="status" value="1" checked data-bootstrap-switch >
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="name">Apellido Paterno</label>
                                             <input type="text" name="last_name_paternal" class="form-control" value="{{ old('last_name_paternal', $user->last_name_paternal) }}" placeholder="Apellido Paterno">
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="last_name_maternal">Apellido Materno</label>
                                             <input type="text" name="last_name_maternal" class="form-control" value="{{ old('last_name_maternal', $user->last_name_maternal) }}" placeholder="Apellido Materno">
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="email">Correo</label>
                                             <input type="email" name="email" class="form-control" value="{{ old('email', $user->email) }}" placeholder="Correo">
                                        </div>
                                   </div>
                              </div>
                         </div>
                         <div class="col-md-12">
                              <hr>
                         </div>
                         <div class="col-md-12">
                              <span class="help-block"> Dejar en blanco para no cambiar la contraseña.</span>
                         </div>
                         <div class="col-md-12">
                              <hr>
                         </div>
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="password">Contraseña</label>
                                   <input type="password" name="password" class="form-control"  placeholder="Contraseña">
                              </div>
                         </div>

                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="password_confirmation">Repite la contraseña</label>
                                   <input type="password" name="password_confirmation" class="form-control"  placeholder="Repite la contraseña">
                              </div>
                         </div>
                    </div>
               </div>
               <div class="card-footer">
                    <button type="submit" class="btn btn-info btn-fill float-right">Editar administrador</button>
                    <a href="{{ route('admin.user.index') }}" class="btn btn-default btn-fill float-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>
@stop

<!-- Escripts pasarlos al layout -->
@push('scripts')
<script src="{{ asset('/theme/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>
<script>
$(function () {
     $("input[data-bootstrap-switch]").each(function(){
          $(this).bootstrapSwitch('state', $(this).prop('checked'));
     });
});
</script>

@endpush

resources/views/admin/users/index.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-12">
     <div class="card ">
          <div class="card-header ">
               <h3 class="card-title">Administradores</h3>
               <div class="card-tools">
                    <a href="{{ route('admin.user.create') }}" class="btn btn-success btn-sm">
                         <i class="fa fa-plus"></i> Nuevo
                    </a>
               </div>
          </div>
          <div class="card-body table-responsive">
               <table class="table table-hover table-striped table_js">
                    <thead>
                         <tr>
                              <th>ID</th>
                              <th>Nombre</th>
                              <th>Correo</th>
                              <th class="text-center">Estatus</th>
                              <th class="text-center"><i class="nc-icon nc-preferences-circle-rotate"></i></th>
                         </tr>
                    </thead>
                    <tbody>
                         @foreach ($users as $user)
                         <tr>
                              <td>{{ $user->id }}</td>
                              <td>{{ $user->name }} {{ $user->last_name_paternal }} {{ $user->last_name_maternal }}</td>
                              <td>{{ $user->email }}</td>
                              <td class="text-center">
                                   @if($user->status == 1)
                                        <h6><span class="badge badge-success">Activo</span></h6>
                                   @else
                                        <h6><span class="badge badge-danger">Inactivo</span></h6>
                                   @endif
                              </td>
                              <td class="text-center">
                                   <!-- <a href="{{ route('admin.user.show', $user) }}"
                                        class="btn btn-sm  btn-outline-primary"
                                   > <i class="fas fa-address-card"></i> </a> -->

                                   <a href="{{ route('admin.user.edit', $user) }}"
                                        class="btn btn-sm btn-outline-info"
                                   > <i class="fas fa-user-edit"></i> </a>

                                   <form method="POST"
                                        action="{{ route('admin.user.destroy', $user) }}"
                                        style="display:inline">
                                        {{ csrf_field() }} {{ method_field('DELETE') }}
                                        <button class="btn btn-sm btn-outline-danger"
                                             onclick="return confirm('¿ Estás seguro de querer eliminar este administrador ?')"
                                         >
                                        <i class="fas fa-user-times"></i>
                                        </button>
                                   </form>
                              </td>
                         </tr>
                         @endforeach
                    </tbody>
               </table>
          </div>
     </div>
</div>
@stop