routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');

Auth::routes();

Route::get('data_view_json', 'PageController@data_view_json')->name('data_view_json');
Route::get('testimonials/{id}', 'PageController@testimonials')->name('testimonials');
Route::post('register_appointment', 'Admin\QuotesController@register_appointment')->name('register_appointment');
Route::post('save_testimonial', 'PageController@save_testimonial')->name('save_testimonial');

Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('calendar', 'CalendarController', ['as' => 'admin']);
     Route::resource('quotes', 'QuotesController', ['as' => 'admin']);
     Route::resource('packages', 'PackagesController', ['as' => 'admin']);
     Route::resource('configuration', 'ConfigurationController', ['as' => 'admin']);
     Route::resource('testimonials', 'TestimonialsController', ['as' => 'admin']);
     Route::resource('gallery', 'GalleryController', ['as' => 'admin']);
     Route::resource('cleaning_need', 'CleaningNeedsController', ['as' => 'admin']);
     Route::resource('contact_images', 'ContactImagesController', ['as' => 'admin']);
     Route::resource('disable_day', 'DisableDayController', ['as' => 'admin']);
     Route::get('quotes/finish_quote/{id}', 'QuotesController@finish_quote')->name('admin.quotes.finish_quote');

});

app/Testimonials.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Testimonials extends Model
{
    //
    protected $fillable = [
       'quote_id', 'qualification', 'description', 'on_page'
   ];

   public function quote()
   {
        return $this->hasOne(Quotes::class,  'id','quote_id');
   }
}

app/Http/Controllers/Admin/TestimonialsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Testimonials;


class TestimonialsController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index()
     {
          $testimonials = Testimonials::all();
          return view('admin.testimonials.index', compact('testimonials'));
     }

     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create()
     {
          $testimonial = new Testimonials;
          return view('admin.testimonials.create', compact('testimonial'));
     }

     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(Request $request)
     {

          $data = $request->validate([
               'name' => 'required|string|max:255',
               'description' => 'required|string',
               'price' => 'required|regex:/^[0-9]+(\.[0-9][0-9]?)?$/'
          ]);

          $data['status'] = request('status') == 1 ? 1 : 0 ;

          if ($request->file('photo') != null) {
               $photo = $request->file('photo')->store('public');
               $data['photo'] = Storage::url($photo);
          }


          $packages = Packages::create($data)->id;

          if (request('tasks') ) {
               foreach (request('tasks') as $key => $tasks) {
                    $task['name'] = $tasks;
                    $task['package_id'] = $packages;
                    Tasks::create($task);
               }
          }



          return redirect()->route('admin.packages.index')->with('success', 'Paquete registrado');
     }

     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function show(Packages $packages)
     {
          return view('admin.packages.show', compact('packages'));
     }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function edit($id)
     {
          $testimonial = Testimonials::find($id);
          return view('admin.testimonials.edit', compact('testimonial'));
     }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function update(Request $request, $id)
     {
          $testimonial = Testimonials::find($id);

          $data = $request->validate([
               'qualification' => 'required',
               'description' => 'required'
          ]);

          $data['on_page'] = request('on_page') == 1 ? 1 : 0 ;

          $testimonial->update( $data );

          return redirect()->route('admin.testimonials.index')->with('success', 'Testimonial actualizado');
     }

     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id)
     {
          $packages = Packages::find($id);
          $packages->delete();
          return back()->with('success', 'Administrador eliminado');

     }
}

resources/views/admin/testimonials/create.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-8 ml-auto mr-auto">
     <form class="form" method="post" action="{{ route('admin.quotes.store') }}">
          {{ csrf_field() }}

          <div class="card">
               <div class="card-header ">
                    <h3 class="card-title">Nueva cita</h3>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                              <ul class="list-group">
                                   @foreach($errors->all() as $key => $error)
                                   <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                   @endforeach
                              </ul>
                              @endif
                         </div>
                         <div class="col-md-12">
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="name">Nombre</label>
                                             <input type="text" name="name" class="form-control" value="{{ old('name') }}" required placeholder="Nombre">
                                        </div>
                                   </div>
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="email">Teléfono</label><br>
                                             <input type="text" name="phone" class="form-control" value="{{ old('phone') }}" required placeholder="Teléfono" >
                                        </div>
                                   </div>

                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="name">Correo</label>
                                             <input type="email" name="email" class="form-control" value="{{ old('email') }}" required placeholder="Correo">
                                        </div>
                                   </div>

                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="last_name_maternal">Día de visita</label>
                                             <input type="text" name="visit" class="form-control" id="piker" value="{{ old('visit') }}" required placeholder="Día de visita">
                                        </div>
                                   </div>

                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="last_name_maternal">Paquete</label>
                                             <select class="form-control" name="package_id">
                                                  <?php foreach ($packages as $key => $package): ?>
                                                       <option value="{{$package->id}}">{{$package->name}}</option>
                                                  <?php endforeach; ?>
                                             </select>
                                        </div>
                                   </div>

                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="email">Dirección</label>
                                             <textarea name="direction" rows="4" cols="80" class="form-control" required placeholder="Dirección">{{ old('direction') }}</textarea>
                                        </div>
                                   </div>

                              </div>
                         </div>
                    </div>
               </div>
               <div class="card-footer">
                    <button type="submit" class="btn btn-info btn-fill float-right">Agregar cita</button>
                    <a href="{{ route('admin.calendar.index') }}" class="btn btn-default btn-fill float-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>
@stop

@push('style')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">

@endpush


<!-- Escripts pasarlos al layout -->
@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="{{ asset('/theme/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>
<script>
var date = new Date();
date.setDate(date.getDate()+1);
$('#piker').datepicker({
     format: "dd-mm-yyyy",
     autoclose: true,
     todayHighlight: true,
     startDate: date
});
$(function () {
     $("input[data-bootstrap-switch]").each(function(){
          $(this).bootstrapSwitch('state', $(this).prop('checked'));
     });
});
</script>

@endpush

resources/views/admin/testimonials/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-8 ml-auto mr-auto">
     <form class="form" method="post" enctype="multipart/form-data" action="{{ route('admin.testimonials.update', $testimonial) }}">
          {{ csrf_field() }} {{ method_field('PUT') }}
          <div class="card">
               <div class="card-header ">
                    <h3 class="card-title">Nueva cita</h3>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                              <ul class="list-group">
                                   @foreach($errors->all() as $key => $error)
                                   <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                   @endforeach
                              </ul>
                              @endif
                         </div>
                         <div class="col-md-12">
                              <div class="row">

                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="name">Calificación</label><br>
                                             <p class="clasificacion" style="margin-bottom: 5px;">
                                                  <input id="radio1" type="radio" name="qualification" value="5" <?php if ( $testimonial->qualification == 5): ?> checked <?php endif; ?>>
                                                  <label for="radio1">★</label>
                                                  <input id="radio2" type="radio" name="qualification" value="4" <?php if ( $testimonial->qualification == 4): ?> checked <?php endif; ?>>
                                                  <label for="radio2">★</label>
                                                  <input id="radio3" type="radio" name="qualification" value="3" <?php if ( $testimonial->qualification == 3): ?> checked <?php endif; ?>>
                                                  <label for="radio3">★</label>
                                                  <input id="radio4" type="radio" name="qualification" value="2" <?php if ( $testimonial->qualification == 2): ?> checked <?php endif; ?>>
                                                  <label for="radio4">★</label>
                                                  <input id="radio5" type="radio" name="qualification" value="1" <?php if ( $testimonial->qualification == 1): ?> checked <?php endif; ?>>
                                                  <label for="radio5">★</label>
                                             </p>
                                        </div>
                                   </div>
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="name">Ver en la página</label><br>
                                             <input type="checkbox" name="on_page" value="1" <?php if(old('on_page', $testimonial->on_page) == 1): ?> checked <?php endif; ?> data-bootstrap-switch >
                                        </div>
                                   </div>



                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="email">Descripción</label>
                                             <textarea name="description" rows="4" cols="80" class="form-control" required placeholder="Dirección">{{ old('description', $testimonial->description) }}</textarea>
                                        </div>
                                   </div>

                              </div>
                         </div>
                    </div>
               </div>
               <div class="card-footer">
                    <button type="submit" class="btn btn-info btn-fill float-right">Editar cita</button>
                    <a href="{{ route('admin.calendar.index') }}" class="btn btn-default btn-fill float-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>
@stop

@push('style')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<style>
p.clasificacion {
     position: relative;
     overflow: hidden;
     display: inline-block;
}

p.clasificacion input {
     position: absolute;
     top: -100px;
}

p.clasificacion label {
     float: right;
     color: #333;
     font-size: 30px;
}

p.clasificacion label:hover,
p.clasificacion label:hover ~ label,
p.clasificacion input:checked ~ label {
     color: #dd4;
}
</style>
@endpush


<!-- Escripts pasarlos al layout -->
@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="{{ asset('/theme/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>

<script>
$(function () {
     $("input[data-bootstrap-switch]").bootstrapSwitch();
});

var date = new Date();
date.setDate(date.getDate()+1);
$('#piker').datepicker({
     format: "dd-mm-yyyy",
     autoclose: true,
     todayHighlight: true,
     startDate: date
});
$(function () {
     $("input[data-bootstrap-switch]").each(function(){
          $(this).bootstrapSwitch('state', $(this).prop('checked'));
     });
});
</script>

@endpush

resources/views/admin/testimonials/index.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-12">
     <div class="card ">
          <div class="card-header ">
               <h3 class="card-title">Paquetes</h3>

          </div>
          <div class="card-body table-responsive">
               <table class="table table-hover table-striped table_js">
                    <thead>
                         <tr>
                              <th>ID</th>
                              <th>Nombre</th>
                              <th class="text-center">Calificación</th>
                              <th class="text-center">Vista en página</th>
                              <th class="text-center"><i class="nc-icon nc-preferences-circle-rotate"></i></th>
                         </tr>
                    </thead>
                    <tbody>
                         @foreach ($testimonials as $testimonial)
                         <tr>
                              <td>{{ $testimonial->id }}</td>
                              <td>{{ $testimonial->quote->name }}</td>
                              <td class="text-center">{{ $testimonial->qualification }}</td>
                              <td class="text-center">
                                   @if($testimonial->on_page == 1)
                                        <h6><span class="badge badge-success">Activo</span></h6>
                                   @else
                                        <h6><span class="badge badge-danger">Inactivo</span></h6>
                                   @endif
                              </td>

                              <td class="text-center">
                                   <a href="{{ route('admin.testimonials.edit', $testimonial) }}"
                                        class="btn btn-sm btn-outline-info"
                                   > <i class="fas fa-edit"></i> </a>

                              </td>
                         </tr>
                         @endforeach
                    </tbody>
               </table>
          </div>
     </div>
</div>
@stop